/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DynamicComponent {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLDynamicComponentElement extends Components.DynamicComponent, HTMLStencilElement {
    }
    var HTMLDynamicComponentElement: {
        prototype: HTMLDynamicComponentElement;
        new (): HTMLDynamicComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dynamic-component": HTMLDynamicComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DynamicComponent {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "dynamic-component": DynamicComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dynamic-component": LocalJSX.DynamicComponent & JSXBase.HTMLAttributes<HTMLDynamicComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
